/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellAnalysesRouteImport } from './routes/_shell.analyses'
import { Route as ShellJobsRouteImport } from './routes/_shell.jobs'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellCandidatesIndexRouteImport } from './routes/_shell.candidates.index'
import { Route as ShellCandidatesCandidateIdRouteImport } from './routes/_shell.candidates.$candidateId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalysesRoute = ShellAnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => ShellRoute,
} as any)
const ShellJobsRoute = ShellJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCandidatesIndexRoute = ShellCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCandidatesCandidateIdRoute =
  ShellCandidatesCandidateIdRouteImport.update({
    id: '/candidates/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analyses': typeof ShellAnalysesRoute
  '/jobs': typeof ShellJobsRoute
  '/settings': typeof ShellSettingsRoute
  '/candidates/$candidateId': typeof ShellCandidatesCandidateIdRoute
  '/candidates/': typeof ShellCandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analyses': typeof ShellAnalysesRoute
  '/jobs': typeof ShellJobsRoute
  '/settings': typeof ShellSettingsRoute
  '/': typeof ShellIndexRoute
  '/candidates/$candidateId': typeof ShellCandidatesCandidateIdRoute
  '/candidates': typeof ShellCandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_shell/analyses': typeof ShellAnalysesRoute
  '/_shell/jobs': typeof ShellJobsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/candidates/$candidateId': typeof ShellCandidatesCandidateIdRoute
  '/_shell/candidates/': typeof ShellCandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/analyses'
    | '/jobs'
    | '/settings'
    | '/candidates/$candidateId'
    | '/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/analyses'
    | '/jobs'
    | '/settings'
    | '/'
    | '/candidates/$candidateId'
    | '/candidates'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/signup'
    | '/_shell/analyses'
    | '/_shell/jobs'
    | '/_shell/settings'
    | '/_shell/'
    | '/_shell/candidates/$candidateId'
    | '/_shell/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analyses': {
      id: '/_shell/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof ShellAnalysesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/jobs': {
      id: '/_shell/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof ShellJobsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/candidates/': {
      id: '/_shell/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof ShellCandidatesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/candidates/$candidateId': {
      id: '/_shell/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof ShellCandidatesCandidateIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAnalysesRoute: typeof ShellAnalysesRoute
  ShellJobsRoute: typeof ShellJobsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellCandidatesCandidateIdRoute: typeof ShellCandidatesCandidateIdRoute
  ShellCandidatesIndexRoute: typeof ShellCandidatesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnalysesRoute: ShellAnalysesRoute,
  ShellJobsRoute: ShellJobsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellCandidatesCandidateIdRoute: ShellCandidatesCandidateIdRoute,
  ShellCandidatesIndexRoute: ShellCandidatesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
